export const SERVICES: string[] = [
  "Bed Cover Washing",
  "Bed Sheet Washing",
  "Blanket Washing",
  "Comforter Washing",
  "Quilt Washing",
  "Duvet Cover Washing",
  "Mattress Cover Washing",
  "Mosquito Net Washing",
  "Pillowcase Washing",
  "Towel Washing (Face, Hand, Medium, Large)",
  "Couch/Sofa Cover Washing",
  "Cushion Cover Washing",
  "Curtain Washing (Day/Net, Night/Opaque)",
  "Tablecloth Washing",
  "Napkin Washing",
  "Chair Cover Washing",
  "Coat Washing (Regular, Winter, Wool, etc.)",
  "Jacket Washing (Leather, Regular, Suede)",
  "Sweater/Jumper Washing",
  "Cardigan Washing",
  "Hoodie Washing",
  "Vest Washing",
  "Suit Washing (Jacket, Complete)",
  "Trousers/Pants Washing",
  "Jeans Washing",
  "Shorts Washing",
  "Skirt Washing",
  "Shirt Washing (Dress Shirt, Casual)",
  "T-shirt Washing",
  "Polo Shirt Washing",
  "Dress Washing (Ordinary, Night, Wedding, Bridesmaid, Prom, Cocktail)",
  "Gown Washing (Evening, Party)",
  "Pajama Washing",
  "Nightgown Washing",
  "Robe Washing",
  "Lingerie Washing",
  "Undershirt Washing",
  "Underpant(s) Washing",
  "Socks Washing",
  "Stockings Washing",
  "Baby Clothes Washing (0–7 Years)",
  "School Uniform Washing",
  "Traditional Wear Washing (Kitenge, Amida, Kimono, Saree, etc.)",
  "Sportswear Washing (Tracksuits, Jerseys, Kimono, Complete Sets)",
  "Scarf Washing",
  "Shawl Washing",
  "Tie/Bow Tie Washing",
  "Gloves Washing",
  "Cap/Hat/Beanie Washing",
  "Belt Cleaning",
  "Sneakers Cleaning",
  "Shoes Cleaning",
  "Boots Cleaning",
  "Sandals Cleaning",
  "Slippers Cleaning",
  "Leather Jacket Cleaning",
  "Suede Jacket Cleaning",
  "Fur Coat Cleaning",
  "Velvet Item Cleaning",
  "Silk Item Cleaning",
  "Beaded/Embroidered Garment Cleaning",
  "Leather Bag Cleaning",
  "Suitcase Cleaning (Medium, Large, X-Large)",
  "Umbrella Cleaning",
  "Ironing & Steaming Service (Suits, Dresses, Bed Sheets, etc.)",
];
